### ISSUE TITLE
<shopDao.xml>存在问题

### ISSUE THREAD

**Issue by Draymonders** [tyronczt/imooc-o2o#2]
可能是我还没有整体理解项目的关系,说一个我感觉可能存在的BUG
就是 queryShopList 和 queryShopById时候
联合查询 只有shop 和 area 还有 shop_category 关联了.
少了owner  不知道 是不是 不用联合查询owner...

我的更改
```
from
tb_shop s,
tb_area a,
tb_shop_category sc,
tb_person_info owner
where
s.area_id = a.area_id
and s.shop_category_id = sc.shop_category_id
and owner.user_id = s.owner_id
and s.shop_id
```

**Comment by tyronczt** [comment]
你这样写也是对的，因为后期会有用户体系，需要联合查询用户信息。
我还没做到用户这个模块，所有暂时没有加ownerId的查询条件，到后期也会加上。
另外我在shopDao.xml中selectByShopId方法中没加ownerId的查询条件（我已经备注了），在selectShopList方法上有加
