### ISSUE TITLE
我发现手机端服务访问存在乱码情况

### ISSUE THREAD

**Issue by Gabriel-18** [tyronczt/imooc-o2o#3]
有乱码

**Comment by tyronczt** [comment]
http://o2o.tyronblog.com:8088/o2o/front/index 
我这个项目在你那边显示正常吗？
是不是你项目中打包后设置的编码问题

**Comment by baoly** [comment]
> 有乱码

如果是 前端展示乱码,在Controller中添加以下代码
`response.setContentType("application/json;charset=utf-8")`
或者在Controller `@RequestMapping` 中添加`produce="application/json;charset=utf-8"`
